## Configure G4SBS for gmn (Q^2 = 4.5 GeV^2)
/g4sbs/filename        genrp_test.root   ## Output rootfile

## Configure Experiment
/g4sbs/exp             genrp

## Configure the target
/g4sbs/target          LD2
/g4sbs/targlen         15.0 cm           ## Target Length
/g4sbs/rasterx         2.0 mm  #raster size in X
/g4sbs/rastery         2.0 mm  #raster size in Y

## Configure generator settings
/g4sbs/kine            elastic           ## Generator
/g4sbs/beamcur         30 muA
/g4sbs/beamE           4.3 GeV
/g4sbs/thmin           32.5 deg
/g4sbs/thmax           52.5 deg
/g4sbs/phmin           -24 deg
/g4sbs/phmax           24 deg

## Configure standard detector settings
/g4sbs/hcaldist        9.0 m
/g4sbs/hcalvoffset     0.75 m
/g4sbs/sbsclampopt     2                 ## Front and rear field clamps

## Configure GEn-RP analyzer
/g4sbs/genrpAnalyzer 3
/g4sbs/cdetready        false

## Configure the magnets
/g4sbs/bbfield         0
#/g4sbs/48d48field      0
#/g4sbs/tosfield         GEn-RP-SBS_field.table
/g4sbs/48d48field      1
/g4sbs/sbsmagfield     1.21 tesla
/g4sbs/bbang           42.5 deg
/g4sbs/bbdist          1.55 m
/g4sbs/sbsang          24.7 deg
/g4sbs/48D48dist       2.25 m

/g4sbs/keepsdtrackinfo all true
/g4sbs/totalabs false


## Run 100 events
/g4sbs/eventstatusevery 100
/g4sbs/run             55

